### PR TITLE
feat: fix goog.module with default export.

### LINKED ISSUE #186: Support goog.module
One problem with is that scoped symbols appear in a synthetic `$jscomp.scope` namespace, which cannot be emitted as is.

### PR DESCRIPTION
**Pull request by rkirov**
Since default export does not have a fixed symbol name at the export
site, Closure introduces synthetic $jscomp namespace, which needs to be
cleaned-up before emitting.

Closes #186

### CODE REVIEW

File: src/main/java/com/google/javascript/clutz/DeclarationGenerator.java [hunk 1]
```diff
@@ -1112,6 +1124,35 @@ public Void caseProxyObjectType(ProxyObjectType type) {
...
     }
 
+    // When importing a default export it introduces a synthetic type under $jscomp.scope.
+    // import A from './module' -> type.name is $jscomp.scope.A.
+    private String visitSyntheticModuleTypes(ObjectType type) {
+      // It appears that Closure does not have a convenient API to find the module name given the
+      // synthetically generated type for a default export. So we do this the hard way.
+      // From the constructor function, find the raw source file and parse it to extract the
+      // module name.
+      Node source = type.getConstructor().getSource();
```
Comment (mprobst) [inline src/main/java/com/google/javascript/clutz/DeclarationGenerator.java]: maybe extract a `getSourceCode(JSType)` method?

File: src/main/java/com/google/javascript/clutz/DeclarationGenerator.java [hunk 2]
```diff
@@ -944,8 +948,16 @@ public Void caseObjectType(ObjectType type) {
           } else if (type.isDict()) {
             emit("{[key: string]: any}");
           } else if (type.getReferenceName() != null) {
+            String name;
+            // If a class A is declared in goog.module and exported as default, closure
+            // assigns it a synthetic type $jscomp.scope.A.
+            if (type.getReferenceName().contains("$jscomp.scope")) {
```
Comment (mprobst) [inline src/main/java/com/google/javascript/clutz/DeclarationGenerator.java]: Add a comment on why/how/whether that is different for non-default exports? This seems a bit crazy, maybe it's a thing to raise with Closure? I'd expect to get wonky error messages for users, too (`cannot assign blah to type $jscomp.scope.A` - wtf?).

**Comment by mprobst** [comment]
LGTM.

File: src/main/java/com/google/javascript/clutz/DeclarationGenerator.java (hunk 2 above)
Comment (rkirov) [inline src/main/java/com/google/javascript/clutz/DeclarationGenerator.java]: The error actually looks like this:
`Property foo never defined on variable$$module$path$to$usage$file of type A$$module$path$to$definition$of$A`, so the path before `.` gets stripped, but the module path gets appended separately to the back.

File: src/main/java/com/google/javascript/clutz/DeclarationGenerator.java (hunk 1 above)
Comment (rkirov) [inline src/main/java/com/google/javascript/clutz/DeclarationGenerator.java]: done
