### PR TITLE
Add a test to confirm that the closure fix for unresolved type union works in clutz.

### LINKED ISSUE #625: Union of two unresolved types is optimized into a single type
```javascript
/**
 * @param {Foo|Bar} a
 */
```

is emitted as `a: Foo`

This is a closure bug, so it would be best to fix in closure.

### PR DESCRIPTION
**Pull request by LucasSloan**
Fixes #625

### CODE REVIEW

File: src/test/java/com/google/javascript/clutz/partial/type_union.js [hunk 1]
```diff
@@ -0,0 +1,8 @@
+goog.provide("func");
+goog.require("Foo");
+goog.require("Bar");
+
+/**
+ * @param {Foo|Bar} a
```
Comment (rkirov) [inline src/test/java/com/google/javascript/clutz/partial/type_union.js]: !Foo | !Bar to make the test tighter
