### PR TITLE
fix: do not emit .prototype as a type.

### LINKED ISSUE #206: do not emit `A.prototype` types
In closure it appear that `A.prototype` is a valid type. In fact we emit it in type position for jquery.fn coming from this declaration

https://github.com/google/closure-compiler/blob/master/contrib/externs/jquery-1.9.js#L867

looks like it is not decided how to type that in a .d.ts:

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/jquery/jquery.d.ts#L934

and this case is obscure enough. I suggest just emitting `any` for the `prototype` type.

### PR DESCRIPTION
**Pull request by rkirov**
This can happen very rarely (Foo.prototype is not a valid type symbol in
Closure either), but jquery externs manages to produce it by
setting:

jQuery.fn = jQuery.prototype.

Closes #206

### CODE REVIEW

File: src/main/java/com/google/javascript/clutz/DeclarationGenerator.java [hunk 1]
```diff
@@ -960,6 +960,14 @@ public Void caseObjectType(ObjectType type) {
             } else {
               name = getAbsoluteName(type);
             }
+            // Under special conditions (see prototype_inferred_type.js) closure can infer
+            // the type be the prototype object. Typescript has nothing that matches the shape
```
Comment (mprobst) [inline src/main/java/com/google/javascript/clutz/DeclarationGenerator.java]: nit: Type[S]cript.

File: src/resources/third_party_externs.js [hunk 2]
```diff
@@ -122,9 +122,4 @@ var ClassNamespace = function() {};
...
  * @const
  */
-ClassNamespace.constObj = {};
-
-/**
- * @type {number}
- */
-ClassNamespace.constObj.num;
\ No newline at end of file
+ClassNamespace.constObj = {};
```
Comment (mprobst) [inline src/resources/third_party_externs.js]: Is this change related?

**Comment by mprobst** [comment]
LGTM.

File: src/resources/third_party_externs.js (hunk 2 above)
Comment (rkirov) [inline src/resources/third_party_externs.js]: nope, thanks for catching it.

File: src/main/java/com/google/javascript/clutz/DeclarationGenerator.java (hunk 1 above)
Comment (rkirov) [inline src/main/java/com/google/javascript/clutz/DeclarationGenerator.java]: done.
