### PR TITLE
fix: handle empty union types.

### LINKED ISSUE #141: null type is not emitted in `function(null=)`
example https://github.com/google/closure-library/blob/28d9db61f5dc639c010be74e4d61682121d2dbd7/closure/goog/soy/soy.js#L116

### PR DESCRIPTION
**Pull request by mprobst**
Union types can end up having no legal branch, e.g. with `null=`. Emit an `any`
type for those cases - `any` is TypeScript's closest representation for a
Null Type / Bottom Type.

Fixes #141.

### CODE REVIEW

File: src/test/java/com/google/javascript/clutz/null_type.js [hunk 1]
```diff
@@ -0,0 +1,7 @@
+goog.provide('lefunc');
+
+/**
+ * @param {null} a
+ * @param {null=} b
+ */
+lefunc = function(a, b) {};
```
Comment (rkirov) [inline src/test/java/com/google/javascript/clutz/null_type.js]: doesn't test the change, ie. union type.

File: src/test/java/com/google/javascript/clutz/null_type.js [hunk 2]
```diff
@@ -0,0 +1,7 @@
+goog.provide('lefunc');
```
Comment (rkirov) [inline src/test/java/com/google/javascript/clutz/null_type.js]: 'le func' is this french for 'the funk'? Probably want `nullTypes`.

File: src/test/java/com/google/javascript/clutz/null_type.js (hunk 1 above)
Comment (rkirov) [inline src/test/java/com/google/javascript/clutz/null_type.js]: duh, `null=` is `null|undefined`.

**Comment by rkirov** [comment]
LGTM.

File: src/test/java/com/google/javascript/clutz/null_type.js (hunk 1 above)
Comment (mprobst) [inline src/test/java/com/google/javascript/clutz/null_type.js]: :-)

File: src/test/java/com/google/javascript/clutz/null_type.js (hunk 2 above)
Comment (mprobst) [inline src/test/java/com/google/javascript/clutz/null_type.js]: gnagnagnagna. Done.
