### PR TITLE
feat: simplify & fix interface walking.

### LINKED ISSUE #179: Classes nested in interfaces only create var
```js
goog.provide('some.Interface');

/** @interface */
some.Interface = function() {};

/** @constructor */
some.Interface.SomeClass = function() {};
```

Generates:

```ts
declare namespace clutz.some.Interface {
  var SomeClass: { new(): clutz.some.Interface.SomeClass };
}
```

Which breaks, because there's no type to refer to later on, only the `var SomeClass` symbol.

### PR DESCRIPTION
**Pull request by mprobst**
Interfaces containing static properties can simply be treated like
namespaces with no default export (`isDefault == false`).

Fixes #179.

### CODE REVIEW

File: src/main/java/com/google/javascript/clutz/DeclarationGenerator.java [hunk 1]
```diff
@@ -368,9 +368,7 @@ public int compare(TypedVar o1, TypedVar o2) {
     // static methods. TS does not support static methods on interfaces, thus we create a new
     // namespace for them.
     if (isDefault && isInterfaceWithStatic(symbol.getType())) {
-      emitNamespaceBegin(symbol.getName());
-      treeWalker.walkDefaultInterface((FunctionType) symbol.getType());
-      emitNamespaceEnd();
+      declareNamespace(symbol.getName(), symbol, false, compiler, provides, isExtern);
```
Comment (rkirov) [inline src/main/java/com/google/javascript/clutz/DeclarationGenerator.java]: yey, recursion. You can add comment isDefault false guarantees termination, so that some further refactoring doesn't get us into infinite loops.

**Comment by rkirov** [comment]
LGTM.

File: src/main/java/com/google/javascript/clutz/DeclarationGenerator.java (hunk 1 above)
Comment (mprobst) [inline src/main/java/com/google/javascript/clutz/DeclarationGenerator.java]: Done.
