### PR TITLE
Test case for Function typed fields.

### LINKED ISSUE #171: Field annotated with @const @private {!Function} gets converted to broken ctor
```js
/**
 * The real set timeout for reference.
 * @const @private {!Function}
 */
goog.testing.MockClock.REAL_SETTIMEOUT_ = goog.global.setTimeout;
```

ends up begin:

```ts
class REAL_SETTIMEOUT_ extends tempCtor {
    constructor ( ...a : any [] ) ;
    static bind (a : any ,  ...b ? : any [] ) : ( ...a : any [] ) => any ;
}
```

### PR DESCRIPTION
**Pull request by mprobst**
Fixes #171.

### CODE REVIEW

File: src/main/java/com/google/javascript/clutz/DeclarationGenerator.java [hunk 1]
```diff
@@ -401,22 +401,27 @@ private boolean isNativeObjectType(JSType type, Compiler compiler) {
...
+        return true;
+      }
     }
     return false;
   }
 
   /**
-   * Confusingly, the typedef type returns true on isConstructor checks, so we need to filter
-   * the NoType through this utility method.
+   * Returns true for types that are class like, i.e. that define a constructor for a nested type.
```
Comment (rkirov) [inline src/main/java/com/google/javascript/clutz/DeclarationGenerator.java]: Are interfaces and enums classlike (conceptually and according to the function check). Expand the comment - "constructor for a nested type" does not tell me enough to use this method, feels based on callsites not based on function body.

File: src/test/java/com/google/javascript/clutz/abstract_method.js [hunk 2]
```diff
@@ -0,0 +1,44 @@
+goog.provide('abstract_method.Interface');
+goog.provide('abstract_method.Clazz');
+goog.provide('abstract_method.Child');
+
+/**
+ * When defining a class Foo with an abstract method bar(), you can do:
+ * Foo.prototype.bar = goog.abstractMethod
```
Comment (rkirov) [inline src/test/java/com/google/javascript/clutz/abstract_method.js]: add usually defined in closure's base.js

File: src/test/java/com/google/javascript/clutz/abstract_method.d.ts [hunk 3]
```diff
@@ -0,0 +1,39 @@
...
+declare module 'goog:abstract_method.Child' {
+  import alias = ಠ_ಠ.clutz.abstract_method.Child;
+  export default alias;
+}
+declare namespace ಠ_ಠ.clutz.abstract_method {
+  class Clazz implements ಠ_ಠ.clutz.abstract_method.Interface {
+    private noStructuralTyping_: any;
+    //!! In Closure, abstract methods are just methods that have type Function, which corresponds
+    //!! to a TS method that takes any arguments and returns any. Luckily this is compatible for
+    //!! both the super and the subtype.
```
Comment (rkirov) [inline src/test/java/com/google/javascript/clutz/abstract_method.d.ts]: we lucked out here :)

**Comment by rkirov** [comment]
minor comments, LGTM.
