### PR TITLE
fix: do not emit namespaces that collide with static fields in externs.

### LINKED ISSUE #187: emitting namespaces as static fields
The following closure pattern 

```
/**
 * @constructor
 */
function Foo() {}

/** @type {Object}*/
Foo.foo;

/** @type {string}*/
Foo.foo.bar;
```

is currently emitted as

```
class Foo {
  static foo ..
}

namespace Foo.foo {
  var bar: ...
}
```
which is an error in TS.

Real world examples from jquery externs - https://github.com/google/closure-compiler/blob/master/contrib/externs/jquery-1.9.js - `ajaxSettings, fx, support`

### PR DESCRIPTION
**Pull request by rkirov**
Closes #187

### CODE REVIEW

File: src/main/java/com/google/javascript/clutz/DeclarationGenerator.java [hunk 1]
```diff
@@ -272,13 +272,17 @@ private void processExternSymbols() {
       String parentPath = getNamespace(symbol.getName());
       boolean isDefault = isDefaultExport(symbol);
 
+      // skip foo.bar.baz if:
+      // * foo.bar is namespace
+      // * foo.bar is class-like and baz is a static field.
+      // * foo is a class-like and foo.bar is a static field.
```
Comment (mprobst) [inline src/main/java/com/google/javascript/clutz/DeclarationGenerator.java]: maybe move the comments next to the if statements? Might also be interesting to have a note like "these are handled by xxx.", or at least "elsewhere".

**Comment by mprobst** [comment]
LGTM.
