### PR TITLE
Do not promote dotted member assigments to fields

### LINKED ISSUE #357: class field generation incorrectly interprets dotted member assignments as fields
Constructs like `this.w.bar = 5` result in a class field `bar`.

Input:
```
/**
 * @constructor
 */
var A = function() {
  this.w;
  this.w.bar = 'eh';
};
```

output:
```
class A {
  w: any;
  bar: any = 'eh';
}
```

expected output:
```
class A {
  w: any;
  constructor() {
    this.w.bar = 'eh';
  }
}
```

### PR DESCRIPTION
**Pull request by gmoothart**
this.foo.bar = 5 no longer creates a class field bar = 5

fixes #357

### CODE REVIEW

File: src/test/java/com/google/javascript/gents/singleTests/fields.js [hunk 1]
```diff
@@ -11,6 +11,9 @@ var A = function(a) {
   let y = 1;
   /** @type {number} */
   this.z = y + 1;
+
+  this.w;
+  this.w.bar = 'bar';
```
Comment (mprobst) [inline src/test/java/com/google/javascript/gents/singleTests/fields.js]: add a test that just accesses some global variable, `foo.baz = 1;`?

File: src/main/java/com/google/javascript/gents/TypeConversionPass.java [hunk 2]
```diff
@@ -647,8 +647,9 @@ static ClassMemberDeclaration newDeclaration(Node n, Map<String, Node> classes)
     @Nullable
     static ClassMemberDeclaration newDeclarationOnThis(Node n) {
       Node fullName = getFullName(n);
-      // Node MUST start with "this."
-      if (!fullName.isGetProp() || !containsThis(fullName)) {
+      // Node MUST start with "this." and be shallow, i.e. "this.foo".
+      // "this.foo.bar" and other nestings are not declarations and are ignored.
+      if (!fullName.isGetProp() || !fullName.getFirstChild().isThis()) {
```
Comment (mprobst) [inline src/main/java/com/google/javascript/gents/TypeConversionPass.java]: Can you formulate the comment such that it's more obvious that if `getFirstChild().isThis()` is true, this can only be a single `this.x` step because `fullName` is a binary tree, i.e. there cannot be a third and fourth child?

**Comment by gmoothart** [comment]
Comments addressed.
