### PR TITLE
fix: Don't drop @fileoverview comments

### LINKED ISSUE #403: gents drops @fileoverview comments
@fileoverview jsdoc comments are dropped in gents output. I suspect it is because the comment is being tied to the top goog.module and then dropped when that node is dropped.

This may or may not be an issue when using goog.provide, we should investigate that.

input:
```
/** @fileoverview This is a file */
goog.module('A.B');
```

output:
```
<nothing>
```

desired output:
```
/** @fileoverview This is a file */
```

### PR DESCRIPTION
**Pull request by dpurp**
Fixes #403

### CODE REVIEW

File: src/test/java/com/google/javascript/gents/singleTests/module_class2.js [hunk 1]
```diff
@@ -1,3 +1,6 @@
+/**
```
Comment (gmoothart) [inline src/test/java/com/google/javascript/gents/singleTests/module_class2.js]: can you add a fileoverview to a file with goog.provide?

Comment (dpurp) [inline src/test/java/com/google/javascript/gents/singleTests/module_class2.js]: done
